events {}

http {
    upstream ratelimiter {
        server rl1:8080;
        server rl2:8080;
        server rl3:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ratelimiter;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            
        }
    }
    

    
}